FROM golang:1.25-alpine AS builder

# Alpine
RUN apk add --no-cache git build-base
# Debian
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     git build-essential \
#  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./src ./src
COPY ./tests ./tests
