FROM golang:1.25-alpine AS builder

# Alpine
RUN apk add --no-cache git build-base
# Debian
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     git build-essential \
#  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./src ./src
COPY ./test.env .env
COPY ./docs ./docs
# Copy templates

RUN go build -o main ./src/infrastructure/api/cmd/main.go

FROM alpine:latest

WORKDIR /app
COPY ./src/application/shared/templates/emails ./src/application/shared/templates/emails

COPY --from=builder /app/main .
